import { useEffect, useRef, useState } from "react";
import { AppShell } from "./Chrome";
import AudioPlayer from "./AudioPlayer";
import { Timestamp } from "./Dashboard";
import { seekAudio } from "./seek";
import {
  listEvaluations,
  createEvaluation,
  getEvaluation,
  updateEvaluation,
  deleteEvaluation,
  generateScenarios,
  updateScenario,
  deleteScenario,
  deleteScenariosByStatus,
  createRun,
  getRun,
  getQualevalConfig,
} from "./qualevalClient";
import "./App.css";

const DEFAULT_SCENARIO_COUNT = 5;
const MIN_SCENARIO_COUNT = 1;
const MAX_SCENARIO_COUNT = 43;

const TEMPLATES = {
  healthcare: {
    label: "Healthcare",
    color: "#1e7a8c",
    description: [
      "- Calls a patient 48 hours after discharge to check on recovery and symptoms.",
      "- Confirms the patient took prescribed medication and followed discharge instructions.",
      "- Flags any concerning symptom for a nurse callback instead of advising directly.",
      "- Confirms the patient knows how to reach the clinic before the next scheduled follow-up.",
    ].join("\n"),
    requirements: [
      "- Must never offer a diagnosis, medication dosing, or treatment advice - only escalate.",
      "- Must use HIPAA-appropriate language: never confirm patient details to anyone but the verified patient.",
      "- Must escalate to a human nurse immediately for any reported severe or worsening symptom.",
      "- Must disclose it is an automated calling system within the first few seconds of the call.",
    ].join("\n"),
  },
  finance: {
    label: "Finance",
    color: "#8c6b1e",
    description: [
      "- Answers inbound calls about billing, balances, and account status for a retail bank.",
      "- Verifies caller identity before discussing any account-specific detail.",
      "- Handles routine requests (balance, recent transactions, due dates) end-to-end without a human.",
      "- Recognizes disputes and fraud reports as escalation triggers rather than handling them itself.",
    ].join("\n"),
    requirements: [
      "- Must verify caller identity (full name + last 4 of account number) before disclosing any balance or transaction.",
      "- Must never ask the caller to say a full card number, CVV, or SSN out loud.",
      "- Must offer a transfer to a human agent for any dispute, fraud report, or hardship request.",
      "- Must not make promises about loan approval, credit limit changes, or fee waivers.",
    ].join("\n"),
  },
  school: {
    label: "School",
    color: "#7c5cff",
    description: [
      "- Handles parent and student calls to a K-12 front office about attendance, schedules, and general questions.",
      "- Confirms who is calling and their relationship to the student before sharing any student-specific information.",
      "- Routes safety concerns (bullying, injury, a student not where they should be) to a human immediately.",
      "- Can share general school information (hours, calendar, office contact) with anyone.",
    ].join("\n"),
    requirements: [
      "- Must never confirm a student's schedule, attendance, or whereabouts to a caller who hasn't stated they are that student's parent/guardian.",
      "- Must escalate any safety concern immediately rather than attempting to resolve it.",
      "- Must not share another student's information even if the caller names that student.",
      "- Must disclose it is an automated system if asked directly.",
    ].join("\n"),
  },
  custom: {
    label: "Custom",
    color: "#666e78",
    description: "",
    requirements: "",
  },
};

const WORKFLOW_STEPS = [
  "Describe the target agent by phone number, what it does, and what it must always/never do.",
  "QualEval generates a batch of test scenarios - a persona, a situation, and pass/fail criteria for each.",
  "Review and approve the scenarios worth running; reject the rest.",
  "QualEval places a real call for each approved scenario and judges the transcript pass/fail with evidence.",
];

function formatWhen(iso) {
  if (!iso) return "-";
  try {
    return new Date(iso).toLocaleString();
  } catch {
    return iso;
  }
}

function formatTimestamp(tMs) {
  if (tMs === undefined || tMs === null) return null;
  const totalSeconds = Math.round(tMs / 1000);
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return `${minutes}:${String(seconds).padStart(2, "0")}`;
}

function NewEvaluationForm({ onCreated }) {
  const [name, setName] = useState("");
  const [agentPhoneNumber, setAgentPhoneNumber] = useState("");
  const [defaultPhoneNumber, setDefaultPhoneNumber] = useState(null);
  const [description, setDescription] = useState("");
  const [requirements, setRequirements] = useState("");
  const [activeTemplate, setActiveTemplate] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);
  const [nameAutoGenerated, setNameAutoGenerated] = useState(false);

  useEffect(() => {
    getQualevalConfig()
      .then((config) => {
        if (config.agentPhoneNumber) {
          setDefaultPhoneNumber(config.agentPhoneNumber);
          setAgentPhoneNumber((current) => current || config.agentPhoneNumber);
        }
      })
      .catch(() => {});
  }, []);

  const canSubmit = name.trim() && !busy;

  const applyTemplate = (key) => {
    const template = TEMPLATES[key];
    setActiveTemplate(key);
    setDescription(template.description);
    setRequirements(template.requirements);
    setName((current) => {
      if (current.trim() && !nameAutoGenerated) return current;
      return `${template.label} evaluation`;
    });
    setNameAutoGenerated(true);
  };

  const onSubmit = async (e) => {
    e.preventDefault();
    if (!canSubmit) return;
    setBusy(true);
    setError(null);
    try {
      const created = await createEvaluation({
        name: name.trim(),
        agentPhoneNumber: agentPhoneNumber.trim() || null,
        description: description.trim() || null,
        requirements: requirements.trim() || null,
      });
      onCreated(created);
    } catch (err) {
      setError(err.message ?? "Could not create the evaluation.");
    } finally {
      setBusy(false);
    }
  };

  return (
    <form className="qe-create-hero" onSubmit={onSubmit}>
      <h3>New evaluation</h3>
      <ul className="qe-lede-list">
        {WORKFLOW_STEPS.map((step, i) => (
          <li key={i}>{step}</li>
        ))}
      </ul>

      <div className="qe-template-row">
        {Object.entries(TEMPLATES).map(([key, template]) => (
          <button
            key={key}
            type="button"
            className={`qe-template-chip ${activeTemplate === key ? "is-active" : ""}`}
            style={{ "--qe-field-color": template.color }}
            onClick={() => applyTemplate(key)}
          >
            <span className="qe-template-dot" />
            {template.label}
          </button>
        ))}
      </div>

      <div className="qe-field-row-narrow">
        <div className="qe-field" style={{ "--qe-field-color": "#1e7a8c" }}>
          <label htmlFor="qe-name">Evaluation name</label>
          <input
            id="qe-name"
            type="text"
            placeholder="e.g. Order desk agent eval"
            value={name}
            onChange={(e) => {
              setName(e.target.value);
              setNameAutoGenerated(false);
            }}
          />
        </div>

        <div className="qe-field" style={{ "--qe-field-color": "#8c6b1e" }}>
          <label htmlFor="qe-phone">Target agent phone number</label>
          <input
            id="qe-phone"
            type="tel"
            placeholder="+1 555 555 0100"
            value={agentPhoneNumber}
            onChange={(e) => setAgentPhoneNumber(e.target.value)}
          />
        </div>
      </div>
      {defaultPhoneNumber && (
        <p className="qe-field-hint">
          Defaults to this deployment's demo target agent number. Replace it to test a different agent.
        </p>
      )}

      <div className="qe-field-grid">
        <div className="qe-field qe-field-full" style={{ "--qe-field-color": "var(--accent-2)" }}>
          <label htmlFor="qe-description">Description - what does this agent do?</label>
          <textarea id="qe-description" rows={3} value={description} onChange={(e) => setDescription(e.target.value)} />
        </div>

        <div className="qe-field qe-field-full" style={{ "--qe-field-color": "var(--pass)" }}>
          <label htmlFor="qe-requirements">Requirements - what must this agent always/never do?</label>
          <textarea
            id="qe-requirements"
            rows={3}
            value={requirements}
            onChange={(e) => setRequirements(e.target.value)}
          />
        </div>
      </div>

      {error && <p className="error-banner">{error}</p>}

      <div className="call-row">
        <button type="submit" className="btn btn-primary qe-btn-create" disabled={!canSubmit}>
          {busy ? "Creating…" : "Create evaluation →"}
        </button>
      </div>
    </form>
  );
}

function EvaluationList({ evaluations, navigate }) {
  if (evaluations.length === 0) {
    return <p className="pack-note">No evaluations yet. Create one to start generating test scenarios.</p>;
  }
  return (
    <div className="qe-eval-grid">
      {evaluations.map((evaluation) => (
        <button
          key={evaluation.id}
          type="button"
          className="qe-eval-card"
          onClick={() => navigate(`/qualeval/${encodeURIComponent(evaluation.id)}`)}
        >
          <span className="qe-eval-num">#{evaluation.id.slice(0, 8)}</span>
          <h4>{evaluation.name}</h4>
          <p className="qe-eval-target">{evaluation.agentPhoneNumber ?? "no phone number set"}</p>
          <span className="qe-eval-when">created {formatWhen(evaluation.createdAt)}</span>
        </button>
      ))}
    </div>
  );
}

function runStatus(run) {
  if (!run) return { text: "No runs yet", cls: "is-na" };
  if (run.verdict === "pass") return { text: "Pass", cls: "is-pass" };
  if (run.verdict === "fail") return { text: "Fail", cls: "is-flag" };
  if (run.verdict === "in_progress") return { text: "Call in progress…", cls: "is-na" };
  if (run.verdict === "awaiting_evaluation") return { text: "Call complete - awaiting evaluation…", cls: "is-na" };
  if (run.verdict === "error") return { text: `Error: ${run.error ?? "call could not be placed"}`, cls: "is-flag" };
  return { text: "Pending - not yet run", cls: "is-na" };
}

function VerdictPill({ run }) {
  const status = runStatus(run);
  if (run?.verdict !== "pass" && run?.verdict !== "fail") return null;
  return (
    <div className={`qe-verdict-pill ${run.verdict === "pass" ? "is-pass" : "is-fail"}`}>
      <span className="qe-verdict-icon">{run.verdict === "pass" ? "✓" : "✕"}</span>
      <span className="qe-verdict-text">
        <strong>{status.text}</strong>
        {run.assessment && <span>{run.assessment}</span>}
      </span>
    </div>
  );
}

function RunResult({ run }) {
  const audioRef = useRef(null);
  const turns = run?.transcript?.turns ?? [];
  const criterionResults = run?.criterionResults ?? [];
  if (turns.length === 0 && criterionResults.length === 0) return null;

  return (
    <div className="qe-run-result">
      <VerdictPill run={run} />
      {run?.audioRef && (
        <div className="qe-run-audio">
          <AudioPlayer src={run.audioRef} audioRef={audioRef} />
        </div>
      )}
      <div className="qe-run-layout">
        {turns.length > 0 && (
          <div className="qe-transcript-card">
            <h4>Transcript</h4>
            {turns.map((turn, i) => (
              <div key={i} className={`qe-turn qe-turn-${turn.role === "user" ? "caller" : "agent"}`}>
                <span className="qe-turn-avatar">{turn.role === "user" ? "C" : "A"}</span>
                <span className="qe-turn-bubble">
                  {turn.text}
                  {formatTimestamp(turn.tMs) &&
                    (run.audioRef ? (
                      <Timestamp tMs={turn.tMs} onSeek={(tMs) => seekAudio(audioRef, tMs)} />
                    ) : (
                      <span className="qe-turn-time">{formatTimestamp(turn.tMs)}</span>
                    ))}
                </span>
              </div>
            ))}
          </div>
        )}
        {criterionResults.length > 0 && (
          <div className="qe-criteria-card">
            <h4>Criteria results</h4>
            {criterionResults.map((c, i) => (
              <div key={i} className="qe-criterion-row">
                <div className="qe-criterion-head">
                  <span className={`qe-crit-dot ${c.met ? "is-pass" : "is-fail"}`} />
                  {c.criterion}
                </div>
                {!c.met && c.explanation && <div className="qe-evidence-quote">{c.explanation}</div>}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

function EditScenarioForm({ scenario, onSaved, onCancel, busy }) {
  const [name, setName] = useState(scenario.name ?? "");
  const [category, setCategory] = useState(scenario.category ?? "");
  const [persona, setPersona] = useState(scenario.persona ?? "");
  const [situation, setSituation] = useState(scenario.situation ?? "");
  const [callerObjectives, setCallerObjectives] = useState(scenario.callerObjectives ?? "");
  const [expectedBehavior, setExpectedBehavior] = useState(scenario.expectedBehavior ?? "");
  const [evaluationCriteria, setEvaluationCriteria] = useState((scenario.evaluationCriteria ?? []).join("\n"));
  const [error, setError] = useState(null);

  const onSubmit = async (e) => {
    e.preventDefault();
    if (!name.trim()) return;
    setError(null);
    try {
      await onSaved({
        name: name.trim(),
        category: category.trim() || null,
        persona: persona.trim() || null,
        situation: situation.trim() || null,
        callerObjectives: callerObjectives.trim() || null,
        expectedBehavior: expectedBehavior.trim() || null,
        evaluationCriteria: evaluationCriteria
          .split("\n")
          .map((line) => line.trim())
          .filter(Boolean),
      });
    } catch (err) {
      setError(err.message ?? "Could not save these changes.");
    }
  };

  return (
    <form className="qe-scenario-edit-form" onSubmit={onSubmit}>
      <div className="qe-field-row-narrow">
        <div className="qe-field" style={{ "--qe-field-color": "#1e7a8c" }}>
          <label htmlFor={`qe-sc-name-${scenario.id}`}>Name</label>
          <input id={`qe-sc-name-${scenario.id}`} type="text" value={name} onChange={(e) => setName(e.target.value)} />
        </div>
        <div className="qe-field" style={{ "--qe-field-color": "#8c6b1e" }}>
          <label htmlFor={`qe-sc-category-${scenario.id}`}>Category</label>
          <input
            id={`qe-sc-category-${scenario.id}`}
            type="text"
            value={category}
            onChange={(e) => setCategory(e.target.value)}
          />
        </div>
      </div>
      <div className="qe-field-grid">
        <div className="qe-field qe-field-full">
          <label htmlFor={`qe-sc-persona-${scenario.id}`}>Persona</label>
          <textarea
            id={`qe-sc-persona-${scenario.id}`}
            rows={2}
            value={persona}
            onChange={(e) => setPersona(e.target.value)}
          />
        </div>
        <div className="qe-field qe-field-full">
          <label htmlFor={`qe-sc-situation-${scenario.id}`}>Situation</label>
          <textarea
            id={`qe-sc-situation-${scenario.id}`}
            rows={2}
            value={situation}
            onChange={(e) => setSituation(e.target.value)}
          />
        </div>
        <div className="qe-field qe-field-full">
          <label htmlFor={`qe-sc-objectives-${scenario.id}`}>Caller objectives</label>
          <textarea
            id={`qe-sc-objectives-${scenario.id}`}
            rows={2}
            value={callerObjectives}
            onChange={(e) => setCallerObjectives(e.target.value)}
          />
        </div>
        <div className="qe-field qe-field-full">
          <label htmlFor={`qe-sc-behavior-${scenario.id}`}>Expected behavior</label>
          <textarea
            id={`qe-sc-behavior-${scenario.id}`}
            rows={2}
            value={expectedBehavior}
            onChange={(e) => setExpectedBehavior(e.target.value)}
          />
        </div>
        <div className="qe-field qe-field-full">
          <label htmlFor={`qe-sc-criteria-${scenario.id}`}>Evaluation criteria (one per line)</label>
          <textarea
            id={`qe-sc-criteria-${scenario.id}`}
            rows={3}
            value={evaluationCriteria}
            onChange={(e) => setEvaluationCriteria(e.target.value)}
          />
        </div>
      </div>
      {error && <p className="error-banner">{error}</p>}
      <div className="qe-scenario-actions">
        <button type="submit" className="btn-sm primary" disabled={busy || !name.trim()}>
          {busy ? "Saving…" : "Save changes"}
        </button>
        <button type="button" className="btn-sm ghost" onClick={onCancel} disabled={busy}>
          Cancel
        </button>
      </div>
    </form>
  );
}

function ScenarioCard({ scenario, onApprove, onReject, onRun, onDelete, onEdit, busy }) {
  const latestRun = scenario.runs?.[0] ?? null;
  const status = runStatus(latestRun);
  const [confirmingDelete, setConfirmingDelete] = useState(false);
  const [editing, setEditing] = useState(false);

  if (editing) {
    return (
      <div className={`qe-scenario-card is-${scenario.status}`}>
        <div className="qe-scenario-head">
          <h4>{scenario.name}</h4>
          <div className="qe-scenario-badges">
            {scenario.category && <span className="qe-cat-badge">{scenario.category}</span>}
            <span className={`qe-status-chip is-${scenario.status}`}>{scenario.status}</span>
          </div>
        </div>
        <EditScenarioForm
          scenario={scenario}
          busy={busy}
          onCancel={() => setEditing(false)}
          onSaved={async (fields) => {
            await onEdit(scenario, fields);
            setEditing(false);
          }}
        />
      </div>
    );
  }

  return (
    <div className={`qe-scenario-card is-${scenario.status}`}>
      <div className="qe-scenario-head">
        <h4>{scenario.name}</h4>
        <div className="qe-scenario-badges">
          {scenario.category && <span className="qe-cat-badge">{scenario.category}</span>}
          <span className={`qe-status-chip is-${scenario.status}`}>{scenario.status}</span>
        </div>
      </div>

      {(scenario.persona || scenario.situation || scenario.callerObjectives || scenario.expectedBehavior) && (
        <div className="qe-scenario-meta-grid">
          {scenario.persona && (
            <div>
              <div className="qe-meta-k">Persona</div>
              <div className="qe-meta-v">{scenario.persona}</div>
            </div>
          )}
          {scenario.situation && (
            <div>
              <div className="qe-meta-k">Situation</div>
              <div className="qe-meta-v">{scenario.situation}</div>
            </div>
          )}
          {scenario.callerObjectives && (
            <div>
              <div className="qe-meta-k">Caller objectives</div>
              <div className="qe-meta-v">{scenario.callerObjectives}</div>
            </div>
          )}
          {scenario.expectedBehavior && (
            <div>
              <div className="qe-meta-k">Expected behavior</div>
              <div className="qe-meta-v">{scenario.expectedBehavior}</div>
            </div>
          )}
        </div>
      )}

      {scenario.evaluationCriteria?.length > 0 && (
        <ul className="qe-criteria-list">
          {scenario.evaluationCriteria.map((c, i) => (
            <li key={i}>{c}</li>
          ))}
        </ul>
      )}

      <div className="qe-scenario-actions">
        {scenario.status !== "approved" && (
          <button type="button" className="btn-sm primary" onClick={() => onApprove(scenario)} disabled={busy}>
            Approve
          </button>
        )}
        {scenario.status !== "rejected" && (
          <button type="button" className="btn-sm ghost" onClick={() => onReject(scenario)} disabled={busy}>
            Reject
          </button>
        )}
        {scenario.status === "approved" && (
          <button type="button" className="btn-sm primary" onClick={() => onRun(scenario)} disabled={busy}>
            ▶ Run
          </button>
        )}
        <button type="button" className="btn-sm ghost" onClick={() => setEditing(true)} disabled={busy}>
          Edit
        </button>
        {confirmingDelete ? (
          <>
            <span className="qe-delete-confirm-text">Delete this scenario?</span>
            <button
              type="button"
              className="btn-sm danger"
              onClick={() => onDelete(scenario)}
              disabled={busy}
            >
              Confirm delete
            </button>
            <button type="button" className="btn-sm ghost" onClick={() => setConfirmingDelete(false)} disabled={busy}>
              Cancel
            </button>
          </>
        ) : (
          <button type="button" className="btn-sm ghost" onClick={() => setConfirmingDelete(true)} disabled={busy}>
            Delete
          </button>
        )}
      </div>

      {latestRun && latestRun.verdict !== "pass" && latestRun.verdict !== "fail" && (
        <div className="call-row">
          <span className={`finding-status ${status.cls}`}>{status.text}</span>
        </div>
      )}
      <RunResult run={latestRun} />
    </div>
  );
}

function ScenarioCountStepper({ count, onChange }) {
  return (
    <div className="qe-count-row">
      <label>Scenarios to generate</label>
      <div className="qe-count-input">
        <button
          type="button"
          className="qe-count-step"
          onClick={() => onChange(Math.max(MIN_SCENARIO_COUNT, count - 1))}
          disabled={count <= MIN_SCENARIO_COUNT}
        >
          −
        </button>
        <span>{count}</span>
        <button
          type="button"
          className="qe-count-step"
          onClick={() => onChange(Math.min(MAX_SCENARIO_COUNT, count + 1))}
          disabled={count >= MAX_SCENARIO_COUNT}
        >
          +
        </button>
      </div>
      <span className="qe-count-hint">default {DEFAULT_SCENARIO_COUNT} · max {MAX_SCENARIO_COUNT}</span>
    </div>
  );
}

const STATUS_TABS = [
  { key: "pending", label: "Generated" },
  { key: "approved", label: "Accepted" },
  { key: "rejected", label: "Rejected" },
];

function EditEvaluationForm({ evaluation, onSaved, onCancel }) {
  const [name, setName] = useState(evaluation.name ?? "");
  const [agentPhoneNumber, setAgentPhoneNumber] = useState(evaluation.agentPhoneNumber ?? "");
  const [description, setDescription] = useState(evaluation.description ?? "");
  const [requirements, setRequirements] = useState(evaluation.requirements ?? "");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);

  const onSubmit = async (e) => {
    e.preventDefault();
    if (!name.trim()) return;
    setBusy(true);
    setError(null);
    try {
      const updated = await updateEvaluation(evaluation.id, {
        name: name.trim(),
        agentPhoneNumber: agentPhoneNumber.trim() || null,
        description: description.trim() || null,
        requirements: requirements.trim() || null,
      });
      onSaved(updated);
    } catch (err) {
      setError(err.message ?? "Could not save these changes.");
    } finally {
      setBusy(false);
    }
  };

  return (
    <form className="qe-eval-edit-form" onSubmit={onSubmit}>
      <h4>Edit evaluation</h4>
      <div className="qe-field-row-narrow">
        <div className="qe-field" style={{ "--qe-field-color": "#1e7a8c" }}>
          <label htmlFor="qe-edit-name">Evaluation name</label>
          <input id="qe-edit-name" type="text" value={name} onChange={(e) => setName(e.target.value)} />
        </div>
        <div className="qe-field" style={{ "--qe-field-color": "#8c6b1e" }}>
          <label htmlFor="qe-edit-phone">Target agent phone number</label>
          <input
            id="qe-edit-phone"
            type="tel"
            value={agentPhoneNumber}
            onChange={(e) => setAgentPhoneNumber(e.target.value)}
          />
        </div>
      </div>
      <div className="qe-field-grid">
        <div className="qe-field qe-field-full" style={{ "--qe-field-color": "var(--accent-2)" }}>
          <label htmlFor="qe-edit-description">Description - what does this agent do?</label>
          <textarea
            id="qe-edit-description"
            rows={3}
            value={description}
            onChange={(e) => setDescription(e.target.value)}
          />
        </div>
        <div className="qe-field qe-field-full" style={{ "--qe-field-color": "var(--pass)" }}>
          <label htmlFor="qe-edit-requirements">Requirements - what must this agent always/never do?</label>
          <textarea
            id="qe-edit-requirements"
            rows={3}
            value={requirements}
            onChange={(e) => setRequirements(e.target.value)}
          />
        </div>
      </div>
      {error && <p className="error-banner">{error}</p>}
      <div className="call-row">
        <button type="submit" className="btn btn-primary" disabled={busy || !name.trim()}>
          {busy ? "Saving…" : "Save changes"}
        </button>
        <button type="button" className="btn btn-outline" onClick={onCancel} disabled={busy}>
          Cancel
        </button>
      </div>
    </form>
  );
}

function EvaluationDetail({ evaluationId, navigate, path }) {
  const [evaluation, setEvaluation] = useState(null);
  const [loadError, setLoadError] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [genError, setGenError] = useState(null);
  const [feedback, setFeedback] = useState("");
  const [scenarioCount, setScenarioCount] = useState(DEFAULT_SCENARIO_COUNT);
  const [actionError, setActionError] = useState(null);
  const [busyScenarioId, setBusyScenarioId] = useState(null);
  const [editing, setEditing] = useState(false);
  const [confirmingDelete, setConfirmingDelete] = useState(false);
  const [deleteError, setDeleteError] = useState(null);
  const [activeTab, setActiveTab] = useState("pending");
  const [confirmingDeleteAllTab, setConfirmingDeleteAllTab] = useState(false);
  const [deletingAllTab, setDeletingAllTab] = useState(false);
  const [approvingAllTab, setApprovingAllTab] = useState(false);

  const load = async () => {
    try {
      const loaded = await getEvaluation(evaluationId);
      setEvaluation(loaded);
      setLoadError(null);
    } catch (err) {
      setLoadError(err.message ?? "Could not load this evaluation.");
    }
  };

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [evaluationId]);

  const onGenerate = async () => {
    setGenerating(true);
    setGenError(null);
    try {
      await generateScenarios(evaluationId, feedback.trim() || undefined, scenarioCount);
      setFeedback("");
      await load();
    } catch (err) {
      setGenError(err.message ?? "Could not generate scenarios.");
    } finally {
      setGenerating(false);
    }
  };

  const onApprove = async (scenario) => {
    setActionError(null);
    setBusyScenarioId(scenario.id);
    try {
      await updateScenario(scenario.id, { status: "approved" });
      await load();
    } catch (err) {
      setActionError(err.message ?? "Could not approve the scenario.");
    } finally {
      setBusyScenarioId(null);
    }
  };

  const onReject = async (scenario) => {
    setActionError(null);
    setBusyScenarioId(scenario.id);
    try {
      await updateScenario(scenario.id, { status: "rejected" });
      await load();
    } catch (err) {
      setActionError(err.message ?? "Could not reject the scenario.");
    } finally {
      setBusyScenarioId(null);
    }
  };

  const onRun = async (scenario) => {
    setActionError(null);
    setBusyScenarioId(scenario.id);
    try {
      const run = await createRun(scenario.id);
      await getRun(run.id);
      await load();
    } catch (err) {
      setActionError(err.message ?? "Could not create the run.");
    } finally {
      setBusyScenarioId(null);
    }
  };

  const onEditScenario = async (scenario, fields) => {
    setBusyScenarioId(scenario.id);
    try {
      await updateScenario(scenario.id, fields);
      await load();
    } finally {
      setBusyScenarioId(null);
    }
  };

  const onDeleteScenario = async (scenario) => {
    setActionError(null);
    setBusyScenarioId(scenario.id);
    try {
      await deleteScenario(scenario.id);
      await load();
    } catch (err) {
      setActionError(err.message ?? "Could not delete the scenario.");
    } finally {
      setBusyScenarioId(null);
    }
  };

  const onApproveAllInTab = async () => {
    setActionError(null);
    setApprovingAllTab(true);
    try {
      const pending = (evaluation.scenarios ?? []).filter((s) => s.status === "pending");
      for (const scenario of pending) {
        await updateScenario(scenario.id, { status: "approved" });
      }
      await load();
    } catch (err) {
      setActionError(err.message ?? "Could not approve all scenarios.");
    } finally {
      setApprovingAllTab(false);
    }
  };

  const onDeleteAllInTab = async () => {
    setActionError(null);
    setDeletingAllTab(true);
    try {
      await deleteScenariosByStatus(evaluationId, activeTab);
      setConfirmingDeleteAllTab(false);
      await load();
    } catch (err) {
      setActionError(err.message ?? "Could not delete these scenarios.");
    } finally {
      setDeletingAllTab(false);
    }
  };

  const onDeleteEvaluation = async () => {
    setDeleteError(null);
    try {
      await deleteEvaluation(evaluationId);
      navigate("/qualeval");
    } catch (err) {
      setDeleteError(err.message ?? "Could not delete this evaluation.");
    }
  };

  if (loadError) {
    return (
      <AppShell path={path} navigate={navigate} title="QualEval">
        <p className="error-banner">{loadError}</p>
      </AppShell>
    );
  }
  if (!evaluation) {
    return (
      <AppShell path={path} navigate={navigate} title="QualEval">
        <p className="pack-note">Loading…</p>
      </AppShell>
    );
  }

  const scenarios = evaluation.scenarios ?? [];
  const tabCounts = Object.fromEntries(STATUS_TABS.map((t) => [t.key, scenarios.filter((s) => s.status === t.key).length]));
  const visibleScenarios = scenarios.filter((s) => s.status === activeTab);

  return (
    <AppShell
      path={path}
      navigate={navigate}
      title={evaluation.name}
      actions={
        <button type="button" className="btn btn-outline" onClick={() => navigate("/qualeval")}>
          Back to evaluations
        </button>
      }
    >
      <div className="qualeval-page">
        <div className="qe-eval-header-actions">
          {!editing && (
            <button type="button" className="btn-sm ghost" onClick={() => setEditing(true)}>
              Edit evaluation
            </button>
          )}
          {!editing &&
            (confirmingDelete ? (
              <>
                <span className="qe-delete-confirm-text">
                  Delete this evaluation and all its scenarios and runs?
                </span>
                <button type="button" className="btn-sm danger" onClick={onDeleteEvaluation}>
                  Confirm delete
                </button>
                <button type="button" className="btn-sm ghost" onClick={() => setConfirmingDelete(false)}>
                  Cancel
                </button>
              </>
            ) : (
              <button type="button" className="btn-sm ghost" onClick={() => setConfirmingDelete(true)}>
                Delete evaluation
              </button>
            ))}
        </div>
        {deleteError && <p className="error-banner">{deleteError}</p>}

        {editing ? (
          <EditEvaluationForm
            evaluation={evaluation}
            onSaved={(updated) => {
              setEvaluation((prev) => ({ ...prev, ...updated }));
              setEditing(false);
            }}
            onCancel={() => setEditing(false)}
          />
        ) : (
          <ul className="qe-eval-summary">
            <li>
              <strong>Target agent:</strong> {evaluation.agentPhoneNumber ?? "no phone number set"}
            </li>
            {evaluation.description && (
              <li>
                <strong>Description:</strong> {evaluation.description}
              </li>
            )}
            {evaluation.requirements && (
              <li>
                <strong>Requirements:</strong> {evaluation.requirements}
              </li>
            )}
          </ul>
        )}

        <div className="qualeval-review">
          <div className="qualeval-review-scenarios">
            <h2>Scenarios ({scenarios.length})</h2>
            <div className="qe-tab-bar">
              {STATUS_TABS.map((tab) => (
                <button
                  key={tab.key}
                  type="button"
                  className={`qe-tab ${activeTab === tab.key ? "is-active" : ""}`}
                  onClick={() => {
                    setActiveTab(tab.key);
                    setConfirmingDeleteAllTab(false);
                  }}
                >
                  {tab.label}
                  <span className="qe-tab-count">({tabCounts[tab.key]})</span>
                </button>
              ))}
            </div>
            {tabCounts[activeTab] > 0 && (
              <div className="qe-tab-actions">
                {activeTab === "pending" && !confirmingDeleteAllTab && (
                  <button
                    type="button"
                    className="btn-sm primary"
                    onClick={onApproveAllInTab}
                    disabled={approvingAllTab}
                  >
                    {approvingAllTab ? "Approving…" : "Approve all"}
                  </button>
                )}
                {confirmingDeleteAllTab ? (
                  <>
                    <span className="qe-delete-confirm-text">
                      Delete all {tabCounts[activeTab]} scenario{tabCounts[activeTab] === 1 ? "" : "s"} in this tab?
                    </span>
                    <button
                      type="button"
                      className="btn-sm danger"
                      onClick={onDeleteAllInTab}
                      disabled={deletingAllTab}
                    >
                      {deletingAllTab ? "Deleting…" : "Confirm delete all"}
                    </button>
                    <button
                      type="button"
                      className="btn-sm ghost"
                      onClick={() => setConfirmingDeleteAllTab(false)}
                      disabled={deletingAllTab}
                    >
                      Cancel
                    </button>
                  </>
                ) : (
                  <button
                    type="button"
                    className="btn-sm ghost"
                    onClick={() => setConfirmingDeleteAllTab(true)}
                  >
                    Delete all in this tab
                  </button>
                )}
              </div>
            )}
            {actionError && <p className="error-banner">{actionError}</p>}
            {scenarios.length === 0 && <p className="pack-note">No scenarios yet. Generate a batch to get started.</p>}
            {scenarios.length > 0 && visibleScenarios.length === 0 && (
              <p className="pack-note">No scenarios in this tab.</p>
            )}
            {visibleScenarios.map((scenario) => (
              <ScenarioCard
                key={scenario.id}
                scenario={scenario}
                onApprove={onApprove}
                onReject={onReject}
                onRun={onRun}
                onDelete={onDeleteScenario}
                onEdit={onEditScenario}
                busy={busyScenarioId === scenario.id}
              />
            ))}
          </div>

          <div className="qe-feedback-panel">
            <h4>{scenarios.length === 0 ? "Generate scenarios" : "Regenerate with feedback"}</h4>
            <p className="qe-feedback-hint">
              Regenerating replaces every pending/rejected scenario with a new batch; already-approved
              scenarios are kept as-is.
            </p>
            <textarea
              rows={5}
              className="qe-feedback-box"
              placeholder="What should the next batch of scenarios cover differently? e.g. add more edge cases around cancellations."
              value={feedback}
              onChange={(e) => setFeedback(e.target.value)}
            />
            <ScenarioCountStepper count={scenarioCount} onChange={setScenarioCount} />
            {genError && <p className="error-banner">{genError}</p>}
            <button type="button" className="qe-btn-regen" onClick={onGenerate} disabled={generating}>
              {generating ? "Generating…" : scenarios.length === 0 ? "Generate scenarios" : "Regenerate scenarios"}
            </button>
          </div>
        </div>
      </div>
    </AppShell>
  );
}

export default function QualEval({ navigate, path, evaluationId }) {
  const [evaluations, setEvaluations] = useState(null);
  const [loadError, setLoadError] = useState(null);

  const load = async () => {
    try {
      const loaded = await listEvaluations();
      setEvaluations(loaded);
      setLoadError(null);
    } catch (err) {
      setLoadError(err.message ?? "Could not load evaluations.");
    }
  };

  useEffect(() => {
    if (evaluationId) return;
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [evaluationId]);

  if (evaluationId) {
    return <EvaluationDetail evaluationId={evaluationId} navigate={navigate} path={path} />;
  }

  return (
    <AppShell path={path} navigate={navigate} title="QualEval">
      <div className="qualeval-page">
        <p className="app-lede">
          Black-box qualitative acceptance testing for AI voice agents - test one like a real caller would,
          with no access to its internals.
        </p>

        <NewEvaluationForm onCreated={(created) => navigate(`/qualeval/${encodeURIComponent(created.id)}`)} />

        {loadError && <p className="error-banner">{loadError}</p>}
        {evaluations && <EvaluationList evaluations={evaluations} navigate={navigate} />}
      </div>
    </AppShell>
  );
}
